GET https://vwdwtjke27.execute-api.us-east-2.amazonaws.com/prod/animals
###
POST https://vwdwtjke27.execute-api.us-east-2.amazonaws.com/prod/animals
###
PUT https://vwdwtjke27.execute-api.us-east-2.amazonaws.com/prod/animals
###
DELETE https://vwdwtjke27.execute-api.us-east-2.amazonaws.com/prod/animals
###